[default]
src = 'src'
out = 'out'
libs = ['lib']
test = 'test'

solc_version = '0.8.15'
optimizer = true
optimizer_runs = 200
via_ir = true
verbosity = 3

# ignore solc warnings for missing license
ignored_error_codes = [1878]
gas_price = 1


# See more config options https://github.com/gakonst/foundry/tree/master/config
